<script setup>

import {TextInput, Heading, Button, Alert} from "holvit-components";
import {required} from '@vuelidate/validators'
import {useVuelidate} from '@vuelidate/core'
import {reactive, computed, watch, ref} from "vue";

const state = reactive({
  code: "",
  submitting: false,
  wrongCode: false,
});

const form = ref(null);
const submitButton = ref(null);
const codeField = ref(null);

const checkCode = (code) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (code === '123456') {
        resolve();
      } else {
        reject();
      }
    }, 500);
  });
};

const submit = async () => {
  submitButton.value.focus();
  state.submitting = true;
  try {
    await checkCode(state.code);
    alert('logged in!');
  } catch (e) {
    submitButton.value.shake();
    state.wrongCode = true;
    state.code = "";
    codeField.value.focus();
  }
  state.submitting = false;
}

watch(() => state.code, (code) => {
  if (code.length === 6) {
    form.value.requestSubmit();
  }
});

</script>

<template>
  <form class="flex flex-col gap-6" @submit.prevent="submit" ref="form">
    <Heading class="font-bold text-center">Login</Heading>
    <Alert color="danger" :hidden="!state.wrongCode">
      Authentication failed. Please ensure you are using the correct code from your authenticator app.
    </Alert>
    <TextInput
        v-model="state.code"
        caption="Authentication code"
        placeholder="XXXXXX"
        :max-length="6"
        :autofocus="true"
        :required="true"
        inputmode="numeric"
        :disabled="state.submitting"
        :error-text="v$.code.$errors[0]?.$message"
        helper-text="Enter the 6-digit code generated by your authenticator app."
        ref="codeField"
    />
    <Button
        type="submit"
        text="Login"
        color="primary"
        size="lg"
        :click-effect="true"
        :disabled="state.submitting"
        ref="submitButton"
    />
    <a href="/totp-backup" class="text-sm text-fuchsia-800 underline">
      Lost access to your authenticator app?
    </a>
  </form>
</template>

<style scoped>

</style>