<script setup>
import {TextInput, Heading, Button, Checkbox, Alert} from "holvit-components";
import {onMounted, reactive, ref} from "vue";
import authApi from "../holvitApi/authApi.js";
import QRCode from "qrcode";

const props = defineProps({
  token: {
    type: String,
    required: true,
  },
})

const emit = defineEmits(['success'])

const state = reactive({
  code: "",
  secret: "JBSWY3DPEHPK3PXP",
})

const form = ref(null);
const submitButton = ref(null);
const codeField = ref(null);
const qrcodeCanvas = ref(null);

onMounted(async () => {
  try{
    await authApi.getOnboardingTotp(props.token)
  }catch (e){
    console.log(e) // TODO: error handling
  }

  const otpauthUrl = `otpauth://totp/issuer:accountName?secret=${state.secret}&issuer=issuer`
  console.log(otpauthUrl)
  try {
    console.log(qrcodeCanvas)
    await QRCode.toCanvas(qrcodeCanvas.value, otpauthUrl)
  } catch (error) {
    console.error('Error generating QR code', error) //TODO: handle
  }
})

</script>

<template>
  <form class="flex flex-col gap-6" @submit.prevent="submit" ref="form">
    <Heading class="font-bold text-center">Login</Heading>
    <Alert color="primary">
      To enhance your account security, set up Time-based One-Time Password (TOTP). Scan the QR code with an authenticator app (like Google Authenticator or Authy).
    </Alert>
    <Alert color="danger" :hidden="!state.wrongCode">
      Authentication failed. Please ensure you are using the correct code from your authenticator app.
    </Alert>
    <div class="flex justify-center">
      <canvas ref="qrcodeCanvas"></canvas>
    </div>
    <TextInput
        v-model="state.code"
        caption="Authentication code"
        placeholder="XXXXXX"
        :max-length="6"
        :autofocus="true"
        :required="true"
        inputmode="numeric"
        :disabled="state.submitting"
        helper-text="Enter the 6-digit code generated by your authenticator app."
        ref="codeField"
    />
    <Button
        type="submit"
        text="Validate TOTP"
        color="primary"
        size="large"
        :click-effect="true"
        :disabled="state.submitting"
        ref="submitButton"
    />
  </form>
</template>

<style scoped>

</style>